### ISSUE TITLE
unprocessable_mails 

### ISSUE THREAD

**Issue by Hitcher99** [zammad/zammad#1033]
### Infos:

* Used Zammad version: 1.4x -1.5
* Used Zammad installation source: Debian Package
* Operating system: Debian 8.6 Jessie
* Browser + version: Chrome 57/58

### Expected behavior:

Mails should be processed.

### Actual behavior:

some mails are not getting processed by zammad

-- Hello Zammad Team,

we are facing since Version 1.4 an strange issue that more and more Mails are not getting processed by Zammad.
I have some Mails as Example four you. The Problem first faced since Version 1.4.. we are now on Version 1.5 and the Bug seems still to exist. Hope it can be fixed quickly :) 

Sincerely,
Hitcher99

[unprocessable_mail.zip](https://github.com/zammad/zammad/files/969824/unprocessable_mail.zip)

**Comment by internetfreak** [comment]
As far as I can tell, the bug seems to be related to mails sent using greyhound as only customers which use greyhound as client to send the mail get stuck in the "unprocessable" queue. Strange is, that the customers which are now having this problem had sent mails using greyhound before and it worked without any issue so I wonder what's the problem.
Anyway if possible, this should be fixed somehow, at least a hint why it happens would be useful as it disrupts the flow and leads to forgotten mails due to the fact that we are not notified if a mail fails while getting processed

**Comment by martini** [comment]
@Hitcher99 on my setup I can process the emails without any issue. Is it possible to get the log/production.log to see what error messages are logged?

In case of privacy, just send it to support at zammad dot com. Thanks a lot!

**Comment by martini** [comment]
@internetfreak 
> Anyway if possible, this should be fixed somehow, at least a hint why it happens would be useful as it disrupts the flow and leads to forgotten mails due to the fact that we are not notified if a mail fails while getting processed

In the log/production.log you should find additional infos why the mails are not processed. Some snippets would be great.

**Comment by martini** [comment]
Just reopen on feedback. Thanks!

**Comment by Hitcher99** [comment]
Hello Martini

we are still facing the problem that mails are not getting processed by zammad.
The system is up2date patched it seems that there musst be a problem with pictures included in the Mail oder Attachments.

As attachment i have the complete production log.
I also can provide the following mail in private: 3543082a82477f3889b096c5975a8200.eml

`I, [2017-09-27T09:54:48.594405 #161]  INFO -- : fetching imap (outlook.office365.com/william.harrell@ix-tech.de\support port=993,ssl=true,folder=)
I, [2017-09-27T09:54:49.980496 #161]  INFO -- :  - message 1/1
I, [2017-09-27T09:54:51.751003 #161]  INFO -- : header x-zammad-article-preferences found {"send-auto-response"=>true, "is-auto-response"=>false}
E, [2017-09-27T09:54:53.582720 #161] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//3543082a82477f3889b096c5975a8200.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2017-09-27T09:54:53.582770 #161] ERROR -- : Mysql2::Error: closed MySQL connection: ROLLBACK
I, [2017-09-27T09:54:53.980976 #161]  INFO -- : done
E, [2017-09-27T09:54:53.981633 #161] ERROR -- : Can't use Channel::Driver::Imap: #<ActiveRecord::StatementInvalid: Mysql2::Error: closed MySQL connection: BEGIN>
E, [2017-09-27T09:54:53.981670 #161] ERROR -- :`

![pic1](https://user-images.githubusercontent.com/28291540/30907296-90a9f014-a37a-11e7-8592-1996b57b7ffe.JPG)
[production.log](https://github.com/zammad/zammad/files/1336582/production.log)

**Comment by martini** [comment]
@Hitcher99 may I ask, what your current Zammad version is?

**Comment by Hitcher99** [comment]
Hello Martini when i check the VERSION file unter /opt/zammad/VERSION it says 1.5.x

**Comment by martini** [comment]
Thanks for feedback. It seems the problem is a postmaster filter which is generating invalid SQL. After that the database is rejecting any SQL queries. This leads to unprocessable emails.

## Possible solution: 
Just upgrade zu Zammad 2.0. It's fixed that invalid SQL will be created. 

See here for more infos about Zammad 2.0 features as background https://zammad.com/news/release-2-0

**Comment by Hitcher99** [comment]
Thanks Martini for the Help 👍 

i will try out "Zammad 2.0" at Weekend in my development environment. 
Feedback if this solves the problem follows.
