### ISSUE TITLE
Teams Predefined and custom webhook not working in Zammad 6.3.1 deployed with Helm template

### ISSUE THREAD

**Issue by afloquet** [zammad/zammad#5218]
### Used Zammad Version

6.3.1

### Environment

- Installation method: deployment with [Helm template](https://artifacthub.io/packages/helm/zammad/zammad/12.2.0) on OpenShift cluster
- Operating system (if you're unsure: `cat /etc/os-release` ): containers based on Debian 12
- Database + version:  postgresql 15.4
- Elasticsearch version: 8.12.0
- Browser + version: Microsoft Edge 125.0.2535.92 

### Actual behaviour

When configuring a predefined webhook for Teams notification or trying to test with custom payload or fully custom webhook, the notification is not sent and the following log can be found in the scheduler (sensitive information has been replaced) :

```
I, [2024-06-13T11:55:05.004855#1-149120]  INFO -- : 2024-06-13T11:55:05+0000: [Worker(host:zammad-scheduler-5849c4cf98-dqvhm pid:1)] Job TriggerWebhookJob [3443b8bc-3fdc-465e-a388-6bf189bb9f91] from DelayedJob(default) with arguments: [{"_aj_globalid"=>"gid://zammad/Trigger/10"}, {"_aj_globalid"=>"gid://zammad/Ticket/5248"}, nil, {"changes"=>{"Owner"=>["<REPLACED: Name of previous owner>", "<REPLACED: Name of new owner>"], "_aj_symbol_keys"=>[]}, "user_id"=>5, "execution_type"=>"trigger", "event_type"=>"update", "_aj_ruby2_keywords"=>["changes", "user_id", "execution_type", "event_type"]}] (id=2304592) (queue=default) RUNNING
E, [2024-06-13T11:55:05.185525#1-149120] ERROR -- : 2024-06-13T11:55:05+0000: [Worker(host:zammad-scheduler-5849c4cf98-dqvhm pid:1)] Job TriggerWebhookJob [3443b8bc-3fdc-465e-a388-6bf189bb9f91] from DelayedJob(default) with arguments: [{"_aj_globalid"=>"gid://zammad/Trigger/10"}, {"_aj_globalid"=>"gid://zammad/Ticket/5248"}, nil, {"changes"=>{"Owner"=>["<REPLACED: Name of previous owner>", "<REPLACED: Name of new owner>"], "_aj_symbol_keys"=>[]}, "user_id"=>5, "execution_type"=>"trigger", "event_type"=>"update", "_aj_ruby2_keywords"=>["changes", "user_id", "execution_type", "event_type"]}] (id=2304592) (queue=default) FAILED (0 prior attempts) with NoMethodError: undefined method `present ?' for {"Owner"=>["<REPLACED: Name of previous owner>", "<REPLACED: Name of new owner>"]}:Hash
E, [2024-06-13T11:55:05.185606#1-149120] ERROR -- : 2024-06-13T11:55:05+0000: [Worker(host:zammad-scheduler-5849c4cf98-dqvhm pid:1)] Job TriggerWebhookJob [3443b8bc-3fdc-465e-a388-6bf189bb9f91] from DelayedJob(default) with arguments: [{"_aj_globalid"=>"gid://zammad/Trigger/10"}, {"_aj_globalid"=>"gid://zammad/Ticket/5248"}, nil, {"changes"=>{"Owner"=>["<REPLACED: Name of previous owner>", "<REPLACED: Name of new owner>"], "_aj_symbol_keys"=>[]}, "user_id"=>5, "execution_type"=>"trigger", "event_type"=>"update", "_aj_ruby2_keywords"=>["changes", "user_id", "execution_type", "event_type"]}] (id=2304592) (queue=default) FAILED permanently because of 1 consecutive failures
```

We can see that it got triggered but failed with *undefined method present?* for some object that represent changes in ticket while testing. No log is present in the Webhook section of Zammad settings

The webhook as been defined as follow :
![webhook](https://github.com/zammad/zammad/assets/157115710/d9f6735e-8e67-4709-8acb-6f511a85c526)

The trigger has been defined as follow : 
![trigger](https://github.com/zammad/zammad/assets/157115710/95726a94-5eff-4653-9d2f-a1d511f89de9)

When testing outside of Zammad with Postman or equivalent with an equivalent payload, the notification is sent with success and received in Teams. It also fails with same error when testing a custom payload on [Webhook.site](https://webhook.site/)

The install has been upgraded to latest version on regular basis since December 2021 and is fully up to date. No change has been made to any code. Webhooks used to work until december and did not look further into the issue until now when trying to configure a new one.

Your help would be much appreciated

### Expected behaviour

The webhook is triggered, which is reachable in the webhook logs in Zammad and received in Microsoft Teams

### Steps to reproduce the behaviour

1. Zammad deployed with Helm on Openshift and regularly updated with no change
2. Configure a predefined webhook with the URL of an Incoming Webhook connector on Microsoft Teams
3. Configure a trigger to track any open or closed ticket, or for which agent changes
4. Try to change the agent on some ticket
5. Notification is not sent as described above

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by afloquet** [comment]
I can add two more information :

- When trying the webhook from the scheduler container with curl, it succeeds and goes into Teams without a problem
- I also tested adding an email along with the webhook in the trigger : i do get the email correctly but nothing in Microsoft Teams

**Comment by fliebe92** [comment]
Hi @afloquet and thanks for filing this report. The used file for sending out the webhook is somehow broken in French, this is why you're faced with this issue. We will fix it soon.

**Comment by mgruner** [comment]
@afloquet this should be solved in https://github.com/zammad/zammad/commit/7cdd07224f3f6bb8b124e36b5c8ac5128329397b. Please let us know if it works for you.

**Comment by afloquet** [comment]
Hi @mgruner 

Thank you for your answer

Sorry, I could just test this today as it is quite difficult to change live code in our OpenShift system. After requiring some help to access the storage and apply the changes from the mentioned commit, it is still not working. I also applied the latest template version and checked if the code was still the same as https://github.com/zammad/zammad/commit/7cdd07224f3f6bb8b124e36b5c8ac5128329397b

However, the error message changed a bit, not mentioning the lack of `present ?` function.

Now I get a similar output with this :

```
E, [2024-07-02T12:49:36.948992#1-149160] ERROR -- : 2024-07-02T12:49:36+0000: [Worker(host:zammad-scheduler-7dbdd85cf-rwbmz pid:1)] Job TriggerWebhookJob [987607ab-a796-485c-ba50-9f1f2ea56a53] from DelayedJob(default) with arguments: [{"_aj_globalid"=>"gid://zammad/Trigger/10"}, {"_aj_globalid"=>"gid://zammad/Ticket/5186"}, nil, {"changes"=>{"State"=>["ouvert", "rappel en attente"], "Owner"=>["<REPLACED: Name of previous owner>", "<REPLACED: Name of new owner>"], "Pending till"=>[nil, {"_aj_serialized"=>"ActiveJob::Serializers::TimeWithZoneSerializer", "value"=>"2024-07-05T10:00:00.000000000Z"}], "_aj_symbol_keys"=>[]}, "user_id"=>5, "execution_type"=>"trigger", "event_type"=>"update", "_aj_ruby2_keywords"=>["changes", "user_id", "execution_type", "event_type"]}] (id=2340252) (queue=default) FAILED (0 prior attempts) with NoMethodError: undefined method `[]' for nil:NilClass
```

I couldn't find from which code comes the ``NoMethodError: undefined method `[]' for nil:NilClass`` message

Maybe you have something else to apply ?

**Comment by mgruner** [comment]
@afloquet you don't need to patch anything in your Kubernetes. Just switch to the latest zammad image builds such as `6.3.1-76` or later. All commits pushed to `stable` will trigger new image builds.

Regarding your error, we'd need more details or clear reproduction steps in order to be able to investigate this further.

**Comment by afloquet** [comment]
Hi @mgruner,

Thanks for the info, I wasn't aware about it.
I did push the latest template available, which is [this one](https://artifacthub.io/packages/helm/zammad/zammad/12.2.2) and has the version 6.3.1-76, latest available on there.

However, we still get the same error as in my previous message...

**Comment by afloquet** [comment]
Hi there,

Still the same after applying 6.3.1-91 today from [here](https://artifacthub.io/packages/helm/zammad/zammad/12.3.0)
